/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
 

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Fee, FeeInterface } from "../Fee";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "posIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "rewardAmount",
        type: "uint256",
      },
    ],
    name: "getCommission",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Fee__factory {
  static readonly abi = _abi;
  static createInterface(): FeeInterface {
    return new Interface(_abi) as FeeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Fee {
    return new Contract(address, _abi, runner) as unknown as Fee;
  }
}
