/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
 
export type { PoS } from "./PoS";
export * as factories from "./factories";
export { PoS__factory } from "./factories/PoS__factory";
