/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PoSInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "currentIndex"
      | "getBlockSelectorAddress"
      | "getBlockSelectorIndex"
      | "getNonce"
      | "getRewardManagerAddress"
      | "getStakingAddress"
      | "getState"
      | "getSubInstances"
      | "instantiate"
      | "isActive"
      | "isConcerned"
      | "owner"
      | "produceBlock"
      | "renounceOwnership"
      | "terminate"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NewChain" | "OwnershipTransferred" | "Rewarded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "currentIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockSelectorAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockSelectorIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNonce",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardManagerAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakingAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getState",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubInstances",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "instantiate",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isConcerned",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "produceBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "terminate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "currentIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlockSelectorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlockSelectorIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRewardManagerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakingAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getState", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSubInstances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "instantiate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isConcerned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "produceBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "terminate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace NewChainEvent {
  export type InputTuple = [
    index: BigNumberish,
    stakingAddress: AddressLike,
    blockSelectorAddress: AddressLike,
    workerAuthAddress: AddressLike,
    minimumDifficulty: BigNumberish,
    initialDifficulty: BigNumberish,
    difficultyAdjustmentParameter: BigNumberish,
    targetInterval: BigNumberish,
    ctsiAddress: AddressLike,
    maxReward: BigNumberish,
    minReward: BigNumberish,
    distNumerator: BigNumberish,
    distDenominator: BigNumberish
  ];
  export type OutputTuple = [
    index: bigint,
    stakingAddress: string,
    blockSelectorAddress: string,
    workerAuthAddress: string,
    minimumDifficulty: bigint,
    initialDifficulty: bigint,
    difficultyAdjustmentParameter: bigint,
    targetInterval: bigint,
    ctsiAddress: string,
    maxReward: bigint,
    minReward: bigint,
    distNumerator: bigint,
    distDenominator: bigint
  ];
  export interface OutputObject {
    index: bigint;
    stakingAddress: string;
    blockSelectorAddress: string;
    workerAuthAddress: string;
    minimumDifficulty: bigint;
    initialDifficulty: bigint;
    difficultyAdjustmentParameter: bigint;
    targetInterval: bigint;
    ctsiAddress: string;
    maxReward: bigint;
    minReward: bigint;
    distNumerator: bigint;
    distDenominator: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardedEvent {
  export type InputTuple = [
    index: BigNumberish,
    worker: AddressLike,
    user: AddressLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    index: bigint,
    worker: string,
    user: string,
    reward: bigint
  ];
  export interface OutputObject {
    index: bigint;
    worker: string;
    user: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PoS extends BaseContract {
  connect(runner?: ContractRunner | null): PoS;
  waitForDeployment(): Promise<this>;

  interface: PoSInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  currentIndex: TypedContractMethod<[], [bigint], "view">;

  getBlockSelectorAddress: TypedContractMethod<
    [_index: BigNumberish],
    [string],
    "view"
  >;

  getBlockSelectorIndex: TypedContractMethod<
    [_index: BigNumberish],
    [bigint],
    "view"
  >;

  getNonce: TypedContractMethod<[_index: BigNumberish], [bigint], "view">;

  getRewardManagerAddress: TypedContractMethod<
    [_index: BigNumberish],
    [string],
    "view"
  >;

  getStakingAddress: TypedContractMethod<
    [_index: BigNumberish],
    [string],
    "view"
  >;

  getState: TypedContractMethod<
    [_index: BigNumberish, _user: AddressLike],
    [[boolean, string, bigint]],
    "view"
  >;

  getSubInstances: TypedContractMethod<
    [_index: BigNumberish, arg1: AddressLike],
    [[string[], bigint[]] & { _addresses: string[]; _indices: bigint[] }],
    "view"
  >;

  instantiate: TypedContractMethod<
    [
      _stakingAddress: AddressLike,
      _blockSelectorAddress: AddressLike,
      _workerAuthAddress: AddressLike,
      _minimumDifficulty: BigNumberish,
      _initialDifficulty: BigNumberish,
      _difficultyAdjustmentParameter: BigNumberish,
      _targetInterval: BigNumberish,
      _ctsiAddress: AddressLike,
      _maxReward: BigNumberish,
      _minReward: BigNumberish,
      _distNumerator: BigNumberish,
      _distDenominator: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  isActive: TypedContractMethod<[_index: BigNumberish], [boolean], "view">;

  isConcerned: TypedContractMethod<
    [_index: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  produceBlock: TypedContractMethod<
    [_index: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  terminate: TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "currentIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBlockSelectorAddress"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getBlockSelectorIndex"
  ): TypedContractMethod<[_index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNonce"
  ): TypedContractMethod<[_index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRewardManagerAddress"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getStakingAddress"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getState"
  ): TypedContractMethod<
    [_index: BigNumberish, _user: AddressLike],
    [[boolean, string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubInstances"
  ): TypedContractMethod<
    [_index: BigNumberish, arg1: AddressLike],
    [[string[], bigint[]] & { _addresses: string[]; _indices: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "instantiate"
  ): TypedContractMethod<
    [
      _stakingAddress: AddressLike,
      _blockSelectorAddress: AddressLike,
      _workerAuthAddress: AddressLike,
      _minimumDifficulty: BigNumberish,
      _initialDifficulty: BigNumberish,
      _difficultyAdjustmentParameter: BigNumberish,
      _targetInterval: BigNumberish,
      _ctsiAddress: AddressLike,
      _maxReward: BigNumberish,
      _minReward: BigNumberish,
      _distNumerator: BigNumberish,
      _distDenominator: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[_index: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isConcerned"
  ): TypedContractMethod<
    [_index: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "produceBlock"
  ): TypedContractMethod<[_index: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "terminate"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "NewChain"
  ): TypedContractEvent<
    NewChainEvent.InputTuple,
    NewChainEvent.OutputTuple,
    NewChainEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Rewarded"
  ): TypedContractEvent<
    RewardedEvent.InputTuple,
    RewardedEvent.OutputTuple,
    RewardedEvent.OutputObject
  >;

  filters: {
    "NewChain(uint256,address,address,address,uint256,uint256,uint32,uint32,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      NewChainEvent.InputTuple,
      NewChainEvent.OutputTuple,
      NewChainEvent.OutputObject
    >;
    NewChain: TypedContractEvent<
      NewChainEvent.InputTuple,
      NewChainEvent.OutputTuple,
      NewChainEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Rewarded(uint256,address,address,uint256)": TypedContractEvent<
      RewardedEvent.InputTuple,
      RewardedEvent.OutputTuple,
      RewardedEvent.OutputObject
    >;
    Rewarded: TypedContractEvent<
      RewardedEvent.InputTuple,
      RewardedEvent.OutputTuple,
      RewardedEvent.OutputObject
    >;
  };
}
