/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StakingPoolFactoryImplInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createFlatRateCommission"
      | "createGasTaxCommission"
      | "feeRaiseTimeout"
      | "gasOracle"
      | "getPoS"
      | "maxFeePercentageRaise"
      | "maxGasRaise"
      | "owner"
      | "pause"
      | "paused"
      | "pos"
      | "priceOracle"
      | "referencePool"
      | "renounceOwnership"
      | "setPoSAddress"
      | "setReferencePool"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "NewFlatRateCommissionStakingPool"
      | "NewGasTaxCommissionStakingPool"
      | "OwnershipTransferred"
      | "Paused"
      | "PoSAddressChanged"
      | "ReferencePoolChanged"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createFlatRateCommission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createGasTaxCommission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRaiseTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gasOracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "getPoS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxFeePercentageRaise",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxGasRaise",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "pos", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referencePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPoSAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferencePool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createFlatRateCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createGasTaxCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRaiseTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPoS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxFeePercentageRaise",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxGasRaise",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pos", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referencePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoSAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReferencePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace NewFlatRateCommissionStakingPoolEvent {
  export type InputTuple = [pool: AddressLike, fee: AddressLike];
  export type OutputTuple = [pool: string, fee: string];
  export interface OutputObject {
    pool: string;
    fee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewGasTaxCommissionStakingPoolEvent {
  export type InputTuple = [pool: AddressLike, fee: AddressLike];
  export type OutputTuple = [pool: string, fee: string];
  export interface OutputObject {
    pool: string;
    fee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoSAddressChangedEvent {
  export type InputTuple = [_pos: AddressLike];
  export type OutputTuple = [_pos: string];
  export interface OutputObject {
    _pos: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferencePoolChangedEvent {
  export type InputTuple = [pool: AddressLike];
  export type OutputTuple = [pool: string];
  export interface OutputObject {
    pool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StakingPoolFactoryImpl extends BaseContract {
  connect(runner?: ContractRunner | null): StakingPoolFactoryImpl;
  waitForDeployment(): Promise<this>;

  interface: StakingPoolFactoryImplInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createFlatRateCommission: TypedContractMethod<
    [commission: BigNumberish],
    [string],
    "payable"
  >;

  createGasTaxCommission: TypedContractMethod<
    [gas: BigNumberish],
    [string],
    "payable"
  >;

  feeRaiseTimeout: TypedContractMethod<[], [bigint], "view">;

  gasOracle: TypedContractMethod<[], [string], "view">;

  getPoS: TypedContractMethod<[], [string], "view">;

  maxFeePercentageRaise: TypedContractMethod<[], [bigint], "view">;

  maxGasRaise: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pos: TypedContractMethod<[], [string], "view">;

  priceOracle: TypedContractMethod<[], [string], "view">;

  referencePool: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPoSAddress: TypedContractMethod<[_pos: AddressLike], [void], "nonpayable">;

  setReferencePool: TypedContractMethod<
    [_referencePool: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createFlatRateCommission"
  ): TypedContractMethod<[commission: BigNumberish], [string], "payable">;
  getFunction(
    nameOrSignature: "createGasTaxCommission"
  ): TypedContractMethod<[gas: BigNumberish], [string], "payable">;
  getFunction(
    nameOrSignature: "feeRaiseTimeout"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gasOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPoS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxFeePercentageRaise"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxGasRaise"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pos"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referencePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPoSAddress"
  ): TypedContractMethod<[_pos: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReferencePool"
  ): TypedContractMethod<[_referencePool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "NewFlatRateCommissionStakingPool"
  ): TypedContractEvent<
    NewFlatRateCommissionStakingPoolEvent.InputTuple,
    NewFlatRateCommissionStakingPoolEvent.OutputTuple,
    NewFlatRateCommissionStakingPoolEvent.OutputObject
  >;
  getEvent(
    key: "NewGasTaxCommissionStakingPool"
  ): TypedContractEvent<
    NewGasTaxCommissionStakingPoolEvent.InputTuple,
    NewGasTaxCommissionStakingPoolEvent.OutputTuple,
    NewGasTaxCommissionStakingPoolEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PoSAddressChanged"
  ): TypedContractEvent<
    PoSAddressChangedEvent.InputTuple,
    PoSAddressChangedEvent.OutputTuple,
    PoSAddressChangedEvent.OutputObject
  >;
  getEvent(
    key: "ReferencePoolChanged"
  ): TypedContractEvent<
    ReferencePoolChangedEvent.InputTuple,
    ReferencePoolChangedEvent.OutputTuple,
    ReferencePoolChangedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "NewFlatRateCommissionStakingPool(address,address)": TypedContractEvent<
      NewFlatRateCommissionStakingPoolEvent.InputTuple,
      NewFlatRateCommissionStakingPoolEvent.OutputTuple,
      NewFlatRateCommissionStakingPoolEvent.OutputObject
    >;
    NewFlatRateCommissionStakingPool: TypedContractEvent<
      NewFlatRateCommissionStakingPoolEvent.InputTuple,
      NewFlatRateCommissionStakingPoolEvent.OutputTuple,
      NewFlatRateCommissionStakingPoolEvent.OutputObject
    >;

    "NewGasTaxCommissionStakingPool(address,address)": TypedContractEvent<
      NewGasTaxCommissionStakingPoolEvent.InputTuple,
      NewGasTaxCommissionStakingPoolEvent.OutputTuple,
      NewGasTaxCommissionStakingPoolEvent.OutputObject
    >;
    NewGasTaxCommissionStakingPool: TypedContractEvent<
      NewGasTaxCommissionStakingPoolEvent.InputTuple,
      NewGasTaxCommissionStakingPoolEvent.OutputTuple,
      NewGasTaxCommissionStakingPoolEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PoSAddressChanged(address)": TypedContractEvent<
      PoSAddressChangedEvent.InputTuple,
      PoSAddressChangedEvent.OutputTuple,
      PoSAddressChangedEvent.OutputObject
    >;
    PoSAddressChanged: TypedContractEvent<
      PoSAddressChangedEvent.InputTuple,
      PoSAddressChangedEvent.OutputTuple,
      PoSAddressChangedEvent.OutputObject
    >;

    "ReferencePoolChanged(address)": TypedContractEvent<
      ReferencePoolChangedEvent.InputTuple,
      ReferencePoolChangedEvent.OutputTuple,
      ReferencePoolChangedEvent.OutputObject
    >;
    ReferencePoolChanged: TypedContractEvent<
      ReferencePoolChangedEvent.InputTuple,
      ReferencePoolChangedEvent.OutputTuple,
      ReferencePoolChangedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
