/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface WorkerManagerAuthManagerImplInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptJob"
      | "authorize"
      | "cancelHire"
      | "deauthorize"
      | "getOwner"
      | "getUser"
      | "hire"
      | "hireAndAuthorize"
      | "isAuthorized"
      | "isAvailable"
      | "isOwned"
      | "isPending"
      | "isRetired"
      | "rejectJob"
      | "retire"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Authorization"
      | "Deauthorization"
      | "JobAccepted"
      | "JobOffer"
      | "JobRejected"
      | "Retired"
  ): EventFragment;

  encodeFunctionData(functionFragment: "acceptJob", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelHire",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deauthorize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "hire", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "hireAndAuthorize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAvailable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOwned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPending",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRetired",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "rejectJob", values?: undefined): string;
  encodeFunctionData(functionFragment: "retire", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "acceptJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "authorize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelHire", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deauthorize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hire", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hireAndAuthorize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwned", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPending", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isRetired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rejectJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "retire", data: BytesLike): Result;
}

export namespace AuthorizationEvent {
  export type InputTuple = [
    user: AddressLike,
    worker: AddressLike,
    dapp: AddressLike
  ];
  export type OutputTuple = [user: string, worker: string, dapp: string];
  export interface OutputObject {
    user: string;
    worker: string;
    dapp: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeauthorizationEvent {
  export type InputTuple = [
    user: AddressLike,
    worker: AddressLike,
    dapp: AddressLike
  ];
  export type OutputTuple = [user: string, worker: string, dapp: string];
  export interface OutputObject {
    user: string;
    worker: string;
    dapp: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobAcceptedEvent {
  export type InputTuple = [worker: AddressLike, user: AddressLike];
  export type OutputTuple = [worker: string, user: string];
  export interface OutputObject {
    worker: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobOfferEvent {
  export type InputTuple = [worker: AddressLike, user: AddressLike];
  export type OutputTuple = [worker: string, user: string];
  export interface OutputObject {
    worker: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobRejectedEvent {
  export type InputTuple = [worker: AddressLike, user: AddressLike];
  export type OutputTuple = [worker: string, user: string];
  export interface OutputObject {
    worker: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RetiredEvent {
  export type InputTuple = [worker: AddressLike, user: AddressLike];
  export type OutputTuple = [worker: string, user: string];
  export interface OutputObject {
    worker: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorkerManagerAuthManagerImpl extends BaseContract {
  connect(runner?: ContractRunner | null): WorkerManagerAuthManagerImpl;
  waitForDeployment(): Promise<this>;

  interface: WorkerManagerAuthManagerImplInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptJob: TypedContractMethod<[], [void], "nonpayable">;

  authorize: TypedContractMethod<
    [_workerAddress: AddressLike, _dappAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  cancelHire: TypedContractMethod<
    [_workerAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  deauthorize: TypedContractMethod<
    [_workerAddress: AddressLike, _dappAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getOwner: TypedContractMethod<
    [_workerAddress: AddressLike],
    [string],
    "view"
  >;

  getUser: TypedContractMethod<[_workerAddress: AddressLike], [string], "view">;

  hire: TypedContractMethod<[_workerAddress: AddressLike], [void], "payable">;

  hireAndAuthorize: TypedContractMethod<
    [_workerAddress: AddressLike, _dappAddress: AddressLike],
    [void],
    "payable"
  >;

  isAuthorized: TypedContractMethod<
    [_workerAddress: AddressLike, _dappAddress: AddressLike],
    [boolean],
    "view"
  >;

  isAvailable: TypedContractMethod<
    [workerAddress: AddressLike],
    [boolean],
    "view"
  >;

  isOwned: TypedContractMethod<
    [_workerAddress: AddressLike],
    [boolean],
    "view"
  >;

  isPending: TypedContractMethod<
    [workerAddress: AddressLike],
    [boolean],
    "view"
  >;

  isRetired: TypedContractMethod<
    [_workerAddress: AddressLike],
    [boolean],
    "view"
  >;

  rejectJob: TypedContractMethod<[], [void], "payable">;

  retire: TypedContractMethod<
    [_workerAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptJob"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorize"
  ): TypedContractMethod<
    [_workerAddress: AddressLike, _dappAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelHire"
  ): TypedContractMethod<[_workerAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deauthorize"
  ): TypedContractMethod<
    [_workerAddress: AddressLike, _dappAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOwner"
  ): TypedContractMethod<[_workerAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<[_workerAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "hire"
  ): TypedContractMethod<[_workerAddress: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "hireAndAuthorize"
  ): TypedContractMethod<
    [_workerAddress: AddressLike, _dappAddress: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "isAuthorized"
  ): TypedContractMethod<
    [_workerAddress: AddressLike, _dappAddress: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAvailable"
  ): TypedContractMethod<[workerAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOwned"
  ): TypedContractMethod<[_workerAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPending"
  ): TypedContractMethod<[workerAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRetired"
  ): TypedContractMethod<[_workerAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "rejectJob"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "retire"
  ): TypedContractMethod<[_workerAddress: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Authorization"
  ): TypedContractEvent<
    AuthorizationEvent.InputTuple,
    AuthorizationEvent.OutputTuple,
    AuthorizationEvent.OutputObject
  >;
  getEvent(
    key: "Deauthorization"
  ): TypedContractEvent<
    DeauthorizationEvent.InputTuple,
    DeauthorizationEvent.OutputTuple,
    DeauthorizationEvent.OutputObject
  >;
  getEvent(
    key: "JobAccepted"
  ): TypedContractEvent<
    JobAcceptedEvent.InputTuple,
    JobAcceptedEvent.OutputTuple,
    JobAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "JobOffer"
  ): TypedContractEvent<
    JobOfferEvent.InputTuple,
    JobOfferEvent.OutputTuple,
    JobOfferEvent.OutputObject
  >;
  getEvent(
    key: "JobRejected"
  ): TypedContractEvent<
    JobRejectedEvent.InputTuple,
    JobRejectedEvent.OutputTuple,
    JobRejectedEvent.OutputObject
  >;
  getEvent(
    key: "Retired"
  ): TypedContractEvent<
    RetiredEvent.InputTuple,
    RetiredEvent.OutputTuple,
    RetiredEvent.OutputObject
  >;

  filters: {
    "Authorization(address,address,address)": TypedContractEvent<
      AuthorizationEvent.InputTuple,
      AuthorizationEvent.OutputTuple,
      AuthorizationEvent.OutputObject
    >;
    Authorization: TypedContractEvent<
      AuthorizationEvent.InputTuple,
      AuthorizationEvent.OutputTuple,
      AuthorizationEvent.OutputObject
    >;

    "Deauthorization(address,address,address)": TypedContractEvent<
      DeauthorizationEvent.InputTuple,
      DeauthorizationEvent.OutputTuple,
      DeauthorizationEvent.OutputObject
    >;
    Deauthorization: TypedContractEvent<
      DeauthorizationEvent.InputTuple,
      DeauthorizationEvent.OutputTuple,
      DeauthorizationEvent.OutputObject
    >;

    "JobAccepted(address,address)": TypedContractEvent<
      JobAcceptedEvent.InputTuple,
      JobAcceptedEvent.OutputTuple,
      JobAcceptedEvent.OutputObject
    >;
    JobAccepted: TypedContractEvent<
      JobAcceptedEvent.InputTuple,
      JobAcceptedEvent.OutputTuple,
      JobAcceptedEvent.OutputObject
    >;

    "JobOffer(address,address)": TypedContractEvent<
      JobOfferEvent.InputTuple,
      JobOfferEvent.OutputTuple,
      JobOfferEvent.OutputObject
    >;
    JobOffer: TypedContractEvent<
      JobOfferEvent.InputTuple,
      JobOfferEvent.OutputTuple,
      JobOfferEvent.OutputObject
    >;

    "JobRejected(address,address)": TypedContractEvent<
      JobRejectedEvent.InputTuple,
      JobRejectedEvent.OutputTuple,
      JobRejectedEvent.OutputObject
    >;
    JobRejected: TypedContractEvent<
      JobRejectedEvent.InputTuple,
      JobRejectedEvent.OutputTuple,
      JobRejectedEvent.OutputObject
    >;

    "Retired(address,address)": TypedContractEvent<
      RetiredEvent.InputTuple,
      RetiredEvent.OutputTuple,
      RetiredEvent.OutputObject
    >;
    Retired: TypedContractEvent<
      RetiredEvent.InputTuple,
      RetiredEvent.OutputTuple,
      RetiredEvent.OutputObject
    >;
  };
}
